In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [2]:
df = np.round(pd.read_csv('../CSVs/50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
df = df.sample(5)
df

,R&D Spend,Administration,Marketing Spend,Profit
9,12.0,11.0,30.0,15.0
40,3.0,12.0,17.0,8.0
23,7.0,11.0,30.0,11.0
0,17.0,14.0,47.0,19.0
45,0.0,12.0,0.0,6.0


In [3]:
df = df.iloc[:,0:-1]
df

,R&D Spend,Administration,Marketing Spend
9,12.0,11.0,30.0
40,3.0,12.0,17.0
23,7.0,11.0,30.0
0,17.0,14.0,47.0
45,0.0,12.0,0.0


In [4]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

C:\Users\Admin\AppData\Local\Temp\ipykernel_1884\766688332.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
C:\Users\Admin\AppData\Local\Temp\ipykernel_1884\766688332.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
C:\Users\Admin\AppData\Local\Temp\ipykernel_1884\766688332.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan


In [5]:
df

,R&D Spend,Administration,Marketing Spend
9,12.0,11.0,30.0
40,NaN,12.0,17.0
23,7.0,11.0,30.0
0,17.0,NaN,47.0
45,0.0,12.0,NaN


In [6]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [7]:
# 0th Iteration
df0

,R&D Spend,Administration,Marketing Spend
9,12.0,11.0,30.0
40,9.0,12.0,17.0
23,7.0,11.0,30.0
0,17.0,11.5,47.0
45,0.0,12.0,31.0


In [8]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
9,12.0,11.0,30.0
40,NaN,12.0,17.0
23,7.0,11.0,30.0
0,17.0,11.5,47.0
45,0.0,12.0,31.0


In [47]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

,Administration,Marketing Spend
9,11.00,30.00
23,11.00,30.00
0,11.06,47.00
45,12.00,31.56


In [10]:
y = df1.iloc[[0,2,3,4],0]
y

9     12.0
23     7.0
0     17.0
45     0.0
Name: R&D Spend, dtype: float64

In [11]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-10.39393939])

In [12]:
df1.iloc[1,0] = 23.14

In [13]:
df1

,R&D Spend,Administration,Marketing Spend
9,12.00,11.0,30.0
40,23.14,12.0,17.0
23,7.00,11.0,30.0
0,17.00,11.5,47.0
45,0.00,12.0,31.0


In [14]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
9,12.00,11.0,30.0
40,23.14,12.0,17.0
23,7.00,11.0,30.0
0,17.00,NaN,47.0
45,0.00,12.0,31.0


In [15]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

,R&D Spend,Marketing Spend
9,12.00,30.0
40,23.14,17.0
23,7.00,30.0
45,0.00,31.0


In [16]:
y = df1.iloc[[0,1,2,4],1]
y

9     11.0
40    12.0
23    11.0
45    12.0
Name: Administration, dtype: float64

In [17]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7.36317348])

In [18]:
df1.iloc[3,1] = 11.06

In [19]:
df1

,R&D Spend,Administration,Marketing Spend
9,12.00,11.00,30.0
40,23.14,12.00,17.0
23,7.00,11.00,30.0
0,17.00,11.06,47.0
45,0.00,12.00,31.0


In [20]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
9,12.00,11.00,30.0
40,23.14,12.00,17.0
23,7.00,11.00,30.0
0,17.00,11.06,47.0
45,0.00,12.00,NaN


In [21]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

,R&D Spend,Administration
9,12.00,11.00
40,23.14,12.00
23,7.00,11.00
0,17.00,11.06


In [22]:
y = df1.iloc[0:4,-1]
y

9     30.0
40    17.0
23    30.0
0     47.0
Name: Marketing Spend, dtype: float64

In [23]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-26.62325893])

In [24]:
df1.iloc[4,-1] = 31.56

In [25]:
# After 1st Iteration
df1

,R&D Spend,Administration,Marketing Spend
9,12.00,11.00,30.00
40,23.14,12.00,17.00
23,7.00,11.00,30.00
0,17.00,11.06,47.00
45,0.00,12.00,31.56


In [26]:
# Subtract 0th iteration from 1st iteration

df1 - df0

,R&D Spend,Administration,Marketing Spend
9,0.00,0.00,0.00
40,14.14,0.00,0.00
23,0.00,0.00,0.00
0,0.00,-0.44,0.00
45,0.00,0.00,0.56


In [27]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

,R&D Spend,Administration,Marketing Spend
9,12.0,11.00,30.00
40,NaN,12.00,17.00
23,7.0,11.00,30.00
0,17.0,11.06,47.00
45,0.0,12.00,31.56


In [28]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-6.94998344])

In [29]:
df2.iloc[1,0] = 23.78

In [30]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7.12949967])

In [31]:
df2.iloc[3,1] = 11.22

In [32]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-38.80930986])

In [33]:
df2.iloc[4,-1] = 31.56

In [34]:
df2

,R&D Spend,Administration,Marketing Spend
9,12.00,11.00,30.00
40,23.78,12.00,17.00
23,7.00,11.00,30.00
0,17.00,11.22,47.00
45,0.00,12.00,31.56


In [35]:
df2 - df1

,R&D Spend,Administration,Marketing Spend
9,0.00,0.00,0.0
40,0.64,0.00,0.0
23,0.00,0.00,0.0
0,0.00,0.16,0.0
45,0.00,0.00,0.0


In [36]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

,R&D Spend,Administration,Marketing Spend
9,12.0,11.00,30.00
40,NaN,12.00,17.00
23,7.0,11.00,30.00
0,17.0,11.22,47.00
45,0.0,12.00,31.56


In [37]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-8.38278661])

In [38]:
df3.iloc[1,0] = 24.57

In [39]:
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7.00549291])

In [40]:
df3.iloc[3,1] = 11.37

In [41]:
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-28.61134915])

In [42]:
df3.iloc[4,-1] = 45.53

In [43]:
df2.iloc[3,1] = 11.22

In [44]:
df3

,R&D Spend,Administration,Marketing Spend
9,12.00,11.00,30.00
40,24.57,12.00,17.00
23,7.00,11.00,30.00
0,17.00,11.37,47.00
45,0.00,12.00,45.53


In [45]:
df3 - df2

,R&D Spend,Administration,Marketing Spend
9,0.00,0.00,0.00
40,0.79,0.00,0.00
23,0.00,0.00,0.00
0,0.00,0.15,0.00
45,0.00,0.00,13.97
